server:
  port: 8080

spring:
  application:
    name: service
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${DATASOURCE_USERNAME:postgres}
    password: ${DATASOURCE_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
    show-sql: true
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB
  liquibase:
    change-log: db/changelog/liquibase-changelog.xml
    database-change-log-table: changelog_${spring.application.name}
    database-change-log-lock-table: changelog_lock_${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include: "*"

jwt:
  secret: ${JWT_SECRET:jdksladklsajdlkasdjlsadkasl}
  expiresAt: 1800000

minio:
  bucket: ${MINIO_BUCKET:data}
  url: ${MINIO_URL:http://localhost:9000}
  accessKey: ${MINIO_ACCESS_KEY:minioadmin}
  secretKey: ${MINIO_SECRET_KEY:minioadmin}

elasticsearch:
  host: ${ELASTICSEARCH_HOST_CORE:localhost}
  port: ${ELASTICSEARCH_PORT:9200}
  username: ${ELASTICSEARCH_USERNAME:elastic}
  password: ${ELASTICSEARCH_PASSWORD:elastic}
  index-names:
    songs: songs