server:
  port: 8080

spring:
  application:
    name: service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: create-drop
    show-sql: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

elasticsearch:
  index-names:
    spotify: spotify
  host: ${ELASTICSEARCH_HOST_CORE:localhost}
  port: ${ELASTICSEARCH_PORT:9200}
  username: ${ELASTICSEARCH_USERNAME:elastic}
  password: ${ELASTICSEARCH_PASSWORD:elastic}

jwt:
  secret: jdksladklsajdlkasdjlsadkasl
  expiresAt: 1800000